import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import axios from 'axios'
import {Search,CalendarDays,Users,DoorOpen,Clock3,LogOut,GraduationCap,Shield,Upload,Download,Plus,Trash2,BarChart3,MessageSquare,UserPlus,RefreshCw,Star,Bell,Send,X} from 'lucide-react'
import './index.css'

const API=import.meta.env.VITE_API_URL||'http://localhost:8000'
const api=axios.create({baseURL:API})
api.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c})
type Lecture={id:number;teacher_name:string;class_name:string;subject_name:string;room_number:string;day_of_week:string;start_time:string;end_time:string}
type User={id:number;name:string;email:string;role:string}
const days=['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY']

function Login({onLogin}:{onLogin:(u:User)=>void}){const [mode,setMode]=useState<'login'|'register'>('login');const [email,setEmail]=useState('student@demo.com'),[password,setPassword]=useState('student123'),[err,setErr]=useState('');const [form,setForm]=useState<any>({name:'',email:'',password:'',role:'STUDENT',class_id:'',enrollment_number:'',employee_id:'',designation:'Assistant Professor'});const [classes,setClasses]=useState<any[]>([])
useEffect(()=>{api.get('/register/classes').then(r=>setClasses(r.data)).catch(()=>{})},[])
async function submit(e:React.FormEvent){e.preventDefault();setErr('');try{if(mode==='login'){const r=await api.post('/auth/login',{email,password});localStorage.setItem('token',r.data.access_token);onLogin((await api.get('/auth/me')).data)}else{await api.post('/auth/register',{...form,class_id:form.class_id?Number(form.class_id):null});setMode('login');setEmail(form.email);setPassword(form.password);setErr('Account created. Sign in now.')}}catch(e:any){setErr(e.response?.data?.detail||'Something went wrong')}}
return <div className="auth-shell"><form onSubmit={submit} className="auth-card"><div className="brand-icon"><GraduationCap/></div><h1>Smart Faculty</h1><p className="muted">Lecture & Timetable Management</p>{mode==='login'?<><input aria-label="email" placeholder="Email" className="field" value={email} onChange={e=>setEmail(e.target.value)}/><input aria-label="password" placeholder="Password" type="password" className="field" value={password} onChange={e=>setPassword(e.target.value)}/></>:<><input className="field" placeholder="Full name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className="field" placeholder="Email" type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="field" placeholder="Password (6+ characters)" type="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select className="field" value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="STUDENT">Student</option><option value="TEACHER">Teacher</option><option value="ADMIN">Admin</option></select>{form.role==='STUDENT'&&<><input className="field" placeholder="Enrollment number" required value={form.enrollment_number} onChange={e=>setForm({...form,enrollment_number:e.target.value})}/><select className="field" required value={form.class_id} onChange={e=>setForm({...form,class_id:e.target.value})}><option value="">Select class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></>}{form.role==='TEACHER'&&<><input className="field" placeholder="Employee ID" required value={form.employee_id} onChange={e=>setForm({...form,employee_id:e.target.value})}/><input className="field" placeholder="Designation" value={form.designation} onChange={e=>setForm({...form,designation:e.target.value})}/></>}</>}{err&&<p className={err.includes('created')?'success-text':'error-text'}>{err}</p>}<button className="primary-btn">{mode==='login'?'Sign in':'Create account'}</button><button type="button" className="link-btn" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?<><UserPlus size={16}/> Create Student / Teacher / Admin account</>: '← Back to sign in'}</button>{mode==='login'&&<div className="demo-box">Demo accounts<br/>Admin: admin@demo.com / admin123<br/>Teacher: teacher@demo.com / teacher123<br/>Student: student@demo.com / student123</div>}</form></div>}

function Nav({page,setPage,user,onLogout}:{page:string;setPage:(x:string)=>void;user:User;onLogout:()=>void}){const items=['Dashboard','Weekly Timetable','Search','Resources',...(user.role==='ADMIN'?['Workload']:[]),...(user.role!=='ADMIN'?['Feedback']:[]),...(user.role==='TEACHER'?['Teacher Notes']:[]),...(user.role==='ADMIN'?['Admin','Import CSV']:[])];return <aside className="sidebar"><div className="sidebar-brand"><div className="brand-small"><GraduationCap size={20}/></div>Smart Faculty</div><div className="role-pill">{user.role}</div>{items.map(x=><button key={x} onClick={()=>setPage(x)} className={`nav-btn ${page===x?'active':''}`}>{x}</button>)}<button onClick={onLogout} className="nav-btn logout"><LogOut size={18}/>Logout</button></aside>}

function LectureTable({rows,onDelete}:{rows:Lecture[];onDelete?:((id:number)=>void)}){return <div className="table-wrap"><table><thead><tr><th>Day</th><th>Time</th><th>Subject</th><th>Teacher</th><th>Class</th><th>Room</th>{onDelete&&<th/>}</tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.day_of_week}</td><td><b>{x.start_time}–{x.end_time}</b></td><td><b>{x.subject_name}</b></td><td>{x.teacher_name}</td><td>{x.class_name}</td><td>{x.room_number}</td>{onDelete&&<td><button className="icon-btn danger" onClick={()=>onDelete(x.id)}><Trash2 size={16}/></button></td>}</tr>)}</tbody></table>{!rows.length&&<div className="empty">No timetable entries found.</div>}</div>}

function App({user,onLogout}:{user:User;onLogout:()=>void}){const [page,setPage]=useState('Dashboard');const [lectures,setLectures]=useState<Lecture[]>([]);const [current,setCurrent]=useState<Lecture|null>(null);const [stats,setStats]=useState<any>({});const [q,setQ]=useState('');const [results,setResults]=useState<Lecture[]>([]);const [nl,setNl]=useState('');const [nlResults,setNlResults]=useState<Lecture[]>([]);const [msg,setMsg]=useState('')
const load=async()=>{try{const cacheBust=Date.now();const [t,c,s]=await Promise.all([api.get('/timetable/today',{params:{_t:cacheBust}}),api.get('/timetable/current',{params:{_t:cacheBust}}),api.get('/dashboard/stats',{params:{_t:cacheBust}})]);setLectures(t.data.lectures);setCurrent(c.data.current);setStats(s.data)}catch{}}
useEffect(()=>{load();const h=()=>load();window.addEventListener('timetable-imported',h);return()=>window.removeEventListener('timetable-imported',h)},[])
const logout=()=>{localStorage.removeItem('token');onLogout()};async function search(){if(!q.trim())return setResults([]);setResults((await api.get('/search',{params:{q}})).data);setPage('Search')};async function ask(){if(!nl.trim())return;const r=await api.get('/nl-query',{params:{question:nl}});setNlResults(r.data.results);setMsg(r.data.answer)};async function del(id:number){if(!confirm('Delete this lecture?'))return;await api.delete('/lectures/'+id);await load()}
return <div className="app-shell"><Nav page={page} setPage={setPage} user={user} onLogout={logout}/><main className="main"><header className="topbar"><div className="search-box"><Search size={18}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Search teacher, class, subject or room..."/></div><button onClick={search} className="search-btn"><Search/></button><div className="user-profile"><span className="user-name">{user.name}</span><small>{user.role}</small></div></header><NotificationPopups user={user}/><div className="content">{page==='Dashboard'&&<Dashboard current={current} lectures={lectures} stats={stats} nl={nl} setNl={setNl} ask={ask} nlResults={nlResults} msg={msg}/>} {page==='Weekly Timetable'&&<Weekly/>}{page==='Search'&&<section className="card"><h2>Search Results</h2><LectureTable rows={results}/></section>}{page==='Resources'&&<Resources/>}{page==='Workload'&&user.role==='ADMIN'&&<Workload/>}{page==='Feedback'&&<Feedback/>}{page==='Teacher Notes'&&user.role==='TEACHER'&&<TeacherNotes/>}{page==='Admin'&&user.role==='ADMIN'&&<Admin lectures={lectures} onDelete={del} reload={load}/>} {page==='Import CSV'&&user.role==='ADMIN'&&<ImportCSV onDone={setMsg}/>}</div></main></div>}

function Dashboard({current,lectures,stats,nl,setNl,ask,nlResults,msg}:{current:Lecture|null;lectures:Lecture[];stats:any;nl:string;setNl:(x:string)=>void;ask:()=>void;nlResults:Lecture[];msg:string}){return <div className="stack"><section className="hero"><div><p className="eyebrow">SMART TIMETABLE</p><h2>Know exactly who is teaching, where and when.</h2><p className="hero-sub">A clearer, brighter control center for your college timetable.</p></div><div className="ask-row"><input value={nl} onChange={e=>setNl(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder='Ask: "Who is teaching CSE-A at 11 AM?"'/><button onClick={ask}>Ask</button></div>{msg&&<p className="hero-message">{msg}</p>}</section>{nlResults.length>0&&<section className="card"><h3>Answer</h3><LectureTable rows={nlResults}/></section>}<section className="stat-grid">{[['Teachers',stats.teachers,Users],['Classes',stats.classes,GraduationCap],['Subjects',stats.subjects,Shield],['Rooms',stats.rooms,DoorOpen],['Today',stats.lectures_today,CalendarDays]].map(([a,b,I]:any)=><div className="stat-card" key={a}><I/><span>{a}</span><b>{b??'-'}</b></div>)}</section><section className="dashboard-grid"><div className="card"><div className="section-head"><h3>Today's Schedule</h3><button className="icon-btn" onClick={()=>window.dispatchEvent(new CustomEvent('timetable-imported'))}><RefreshCw size={17}/></button></div><LectureTable rows={lectures}/></div><div className="current-card">{current?<><p>CURRENTLY IN PROGRESS</p><h3>{current.subject_name}</h3><b>{current.teacher_name}</b><span>{current.class_name} · {current.room_number}</span><strong>{current.start_time}–{current.end_time}</strong></>:<><Clock3/><h3>No lecture currently scheduled</h3><span>Your dashboard will update after a timetable import.</span></>}</div></section></div>}

function Weekly(){const [data,setData]=useState<any>({});const load=()=>api.get('/timetable/weekly',{params:{_t:Date.now()}}).then(r=>setData(r.data));useEffect(()=>{load();const h=()=>load();window.addEventListener('timetable-imported',h);return()=>window.removeEventListener('timetable-imported',h)},[]);return <section className="card overflow"><div className="section-head"><h2>Weekly Timetable</h2><button className="icon-btn" onClick={()=>window.print()}><Download size={18}/></button></div><div className="week-grid">{days.map(d=><div className="day-column" key={d}><h3>{d}</h3>{(data[d]||[]).map((x:Lecture)=><div key={x.id} className="lecture-mini"><b>{x.start_time}–{x.end_time}</b><strong>{x.subject_name}</strong><span>{x.teacher_name}</span><small>{x.class_name} · {x.room_number}</small></div>)}</div>)}</div></section>}

function Resources(){const [day,setDay]=useState('MONDAY'),[start,setStart]=useState('11:00'),[end,setEnd]=useState('12:00'),[teachers,setTeachers]=useState<any[]>([]),[rooms,setRooms]=useState<any[]>([]);async function go(){const [a,b]=await Promise.all([api.get('/teachers/free',{params:{day,start_time:start,end_time:end}}),api.get('/rooms/free',{params:{day,start_time:start,end_time:end}})]);setTeachers(a.data);setRooms(b.data)}return <div className="stack"><section className="card"><h2>Free Teachers & Rooms</h2><div className="control-row"><select className="field" value={day} onChange={e=>setDay(e.target.value)}>{days.map(d=><option key={d}>{d}</option>)}</select><input className="field" type="time" value={start} onChange={e=>setStart(e.target.value)}/><input className="field" type="time" value={end} onChange={e=>setEnd(e.target.value)}/><button className="primary-btn compact" onClick={go}>Find</button></div></section><div className="two-col"><div className="card"><h3>Free Teachers</h3>{teachers.map(x=><p key={x.id} className="list-row">{x.name}</p>)}{!teachers.length&&<p className="muted">Click Find to check availability.</p>}</div><div className="card"><h3>Free Rooms</h3>{rooms.map(x=><p key={x.id} className="list-row">{x.room_number}</p>)}{!rooms.length&&<p className="muted">Click Find to check availability.</p>}</div></div></div>}

function Workload(){const [rows,setRows]=useState<any[]>([]);const load=()=>api.get('/analytics/workload',{params:{_t:Date.now()}}).then(r=>setRows(r.data));useEffect(()=>{load();const h=()=>load();window.addEventListener('timetable-imported',h);return()=>window.removeEventListener('timetable-imported',h)},[]);const max=Math.max(...rows.map(x=>x.hours),1);return <section className="card"><div className="section-head"><div><h2>Teacher Workload Analytics</h2><p className="muted">Weekly teaching load based on the current timetable.</p></div><button className="icon-btn" onClick={load}><RefreshCw size={17}/></button></div><div className="bar-chart">{rows.map(x=><div className="bar-row" key={x.id}><div className="bar-label"><b>{x.name}</b><span>{x.hours} hrs · {x.lectures} lectures</span></div><div className="bar-track"><div className="bar-fill" style={{width:`${Math.max(4,(x.hours/max)*100)}%`}}/></div></div>)}</div>{!rows.length&&<div className="empty">No workload data yet.</div>}</section>}

function Feedback(){const [rating,setRating]=useState(5),[message,setMessage]=useState(''),[sent,setSent]=useState(''),[err,setErr]=useState('');async function send(){try{await api.post('/feedback',{rating,message});setSent('Thanks! Your feedback was submitted.');setMessage('')}catch(e:any){setErr(e.response?.data?.detail||'Could not submit feedback')}}return <section className="card feedback-card"><div className="feedback-icon"><MessageSquare/></div><h2>Feedback</h2><p className="muted">Tell us what would make Smart Faculty better.</p><div className="stars">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>setRating(n)} className={n<=rating?'selected':''}><Star fill="currentColor"/></button>)}</div><textarea className="field textarea" value={message} onChange={e=>setMessage(e.target.value)} placeholder="Share your feedback..."/><button className="primary-btn" onClick={send}>Submit feedback</button>{sent&&<p className="success-text">{sent}</p>}{err&&<p className="error-text">{err}</p>}</section>}

function TeacherNotes(){const [audience,setAudience]=useState<string[]>(['STUDENT']),[message,setMessage]=useState(''),[sent,setSent]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false);const toggle=(role:string)=>setAudience(a=>a.includes(role)?a.filter(x=>x!==role):[...a,role]);async function send(){if(!audience.length)return setErr('Choose Student, Admin, or both.');if(!message.trim())return setErr('Write a note first.');setBusy(true);setErr('');setSent('');try{await api.post('/teacher-notes',{audience,message});setSent('Note sent successfully. It will appear as a pop-up for the selected audience.');setMessage('')}catch(e:any){setErr(e.response?.data?.detail||'Could not send note.')}finally{setBusy(false)}}return <section className="card note-card"><div className="note-hero"><div className="note-icon"><Send/></div><div><p className="eyebrow">TEACHER COMMUNICATION</p><h2>Send a note</h2><p className="muted">Send an important message to students, admins, or both.</p></div></div><h3>Send to</h3><div className="audience-grid"><button className={audience.includes('STUDENT')?'audience-btn selected':''} onClick={()=>toggle('STUDENT')}><GraduationCap/><span><b>Students</b><small>Show a pop-up to all students</small></span></button><button className={audience.includes('ADMIN')?'audience-btn selected':''} onClick={()=>toggle('ADMIN')}><Shield/><span><b>Admins</b><small>Show a pop-up to all admins</small></span></button></div><textarea className="field textarea" maxLength={1200} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Example: Room C-101 is changed to C-204 for today's 11 AM class."/><div className="note-footer"><span className="muted">{message.length}/1200 characters</span><button className="primary-btn" disabled={busy} onClick={send}><Send size={17}/>{busy?'Sending…':'Send note'}</button></div>{sent&&<p className="success-text">{sent}</p>}{err&&<p className="error-text">{err}</p>}</section>}

function NotificationPopups({user}:{user:User}){const [notes,setNotes]=useState<any[]>([]);const storageKey=`dismissedNotifications:${user.id||user.email}`;const load=async()=>{try{const r=await api.get('/notifications',{params:{_t:Date.now()}});const dismissed=JSON.parse(localStorage.getItem(storageKey)||'[]') as number[];setNotes(r.data.filter((x:any)=>!dismissed.includes(x.id)))}catch{}};useEffect(()=>{load();const id=window.setInterval(load,5000);return()=>window.clearInterval(id)},[user.id,user.email]);const close=async(id:number)=>{setNotes(n=>n.filter(x=>x.id!==id));const dismissed=JSON.parse(localStorage.getItem(storageKey)||'[]') as number[];localStorage.setItem(storageKey,JSON.stringify(Array.from(new Set([...dismissed,id])).slice(-200)));try{await api.post(`/notifications/${id}/read`)}catch{}};if(!notes.length)return null;return <div className="notification-stack">{notes.slice(0,3).map(n=><div className="notification-popup" key={n.id}><div className="notification-top"><div className="notification-title"><Bell size={18}/><b>New message from {n.sender}</b></div><button className="notification-close" onClick={()=>close(n.id)}><X size={17}/></button></div><p>{n.message}</p><small>Stored notification · just now</small><button className="notification-read" onClick={()=>close(n.id)}>Got it</button></div>)}</div>}

function Admin({lectures,onDelete,reload}:{lectures:Lecture[];onDelete:(id:number)=>void;reload:()=>void}){
const [teachers,setTeachers]=useState<any[]>([]),[classes,setClasses]=useState<any[]>([]),[subjects,setSubjects]=useState<any[]>([]),[rooms,setRooms]=useState<any[]>([]),[form,setForm]=useState<any>({teacher_id:1,class_id:1,subject_id:1,room_id:1,day_of_week:'MONDAY',start_time:'12:00',end_time:'13:00',lecture_type:'Lecture'}),[err,setErr]=useState(''),[substitute,setSubstitute]=useState<Record<number,number>>({}),[subMsg,setSubMsg]=useState<Record<number,string>>({}),[feedback,setFeedback]=useState<any[]>([]),[audience,setAudience]=useState('ALL'),[teacherUserId,setTeacherUserId]=useState(''),[adminMessage,setAdminMessage]=useState(''),[msgStatus,setMsgStatus]=useState('');
const loadFeedback=()=>api.get('/feedback').then(r=>setFeedback(r.data)).catch(()=>{});
useEffect(()=>{Promise.all([api.get('/teachers'),api.get('/classes'),api.get('/subjects'),api.get('/rooms')]).then(([a,b,c,d])=>{setTeachers(a.data);setClasses(b.data);setSubjects(c.data);setRooms(d.data)});loadFeedback()},[]);
async function add(){try{await api.post('/lectures',form);setErr('Lecture created successfully');reload()}catch(e:any){setErr(Array.isArray(e.response?.data?.detail)?e.response.data.detail.join(' '):e.response?.data?.detail||'Could not create lecture')}}
async function assignSubstitute(lectureId:number){const teacherId=substitute[lectureId];if(!teacherId)return;try{await api.put(`/lectures/${lectureId}/substitute`,null,{params:{teacher_id:teacherId}});setSubMsg({...subMsg,[lectureId]:'Substitute updated'});reload()}catch(e:any){setSubMsg({...subMsg,[lectureId]:e.response?.data?.detail||'Could not update substitute'})}}
async function sendMessage(){if(!adminMessage.trim())return setMsgStatus('Write a message first.');if(audience==='TEACHER'&&!teacherUserId)return setMsgStatus('Select a teacher.');try{const r=await api.post('/admin-messages',{audience,message:adminMessage,teacher_user_id:teacherUserId?Number(teacherUserId):null});setMsgStatus(`Message sent to ${r.data.recipients} recipient(s).`);setAdminMessage('')}catch(e:any){setMsgStatus(e.response?.data?.detail||'Could not send message.')}}
return <section className="stack"><div className="card"><h2>Admin · Manage Lectures</h2><div className="form-grid">{[['teacher_id',teachers,'name'],['class_id',classes,'name'],['subject_id',subjects,'name'],['room_id',rooms,'room_number']].map(([k,arr,label]:any)=><select key={k} className="field" value={form[k]} onChange={e=>setForm({...form,[k]:+e.target.value})}>{arr.map((x:any)=><option key={x.id} value={x.id}>{x[label]}</option>)}</select>)}<select className="field" value={form.day_of_week} onChange={e=>setForm({...form,day_of_week:e.target.value})}>{days.map(d=><option key={d}>{d}</option>)}</select><input type="time" className="field" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/><input type="time" className="field" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/><button onClick={add} className="primary-btn compact"><Plus size={17}/>Create Lecture</button></div>{err&&<p className="success-text">{err}</p>}</div>
<div className="card admin-message-card"><div className="note-hero"><div className="note-icon"><Send/></div><div><p className="eyebrow">ADMIN COMMUNICATION</p><h2>Send a message</h2><p className="muted">Send a stored pop-up message to students or teachers.</p></div></div><div className="form-grid"><select className="field" value={audience} onChange={e=>setAudience(e.target.value)}><option value="ALL">Students + Teachers</option><option value="ALL_STUDENTS">All Students</option><option value="ALL_TEACHERS">All Teachers</option><option value="TEACHER">Specific Teacher</option></select>{audience==='TEACHER'?<select className="field" value={teacherUserId} onChange={e=>setTeacherUserId(e.target.value)}><option value="">Select teacher</option>{teachers.map(t=><option key={t.user_id} value={t.user_id}>{t.name}</option>)}</select>:<div/>}<textarea className="field textarea" maxLength={1200} value={adminMessage} onChange={e=>setAdminMessage(e.target.value)} placeholder="Write an important message..."/><button className="primary-btn compact" onClick={sendMessage}><Send size={17}/>Send message</button></div>{msgStatus&&<p className={msgStatus.startsWith('Message sent')?'success-text':'error-text'}>{msgStatus}</p>}</div>
<div className="card"><div className="section-head"><div><h3>Feedback received</h3><p className="muted">Student and teacher feedback is visible only to administrators.</p></div><button className="icon-btn" onClick={loadFeedback}><RefreshCw size={17}/></button></div><div className="feedback-inbox">{feedback.map(f=><div className="feedback-row" key={f.id}><div><b>{f.user}</b><span className="feedback-role">{f.role}</span><div className="feedback-stars">{'★'.repeat(f.rating)}{'☆'.repeat(5-f.rating)}</div></div><p>{f.message}</p><small>{new Date(f.created_at).toLocaleString()}</small></div>)}{!feedback.length&&<div className="empty">No feedback received yet.</div>}</div></div>
<div className="card"><div className="section-head"><div><h3>Existing Lectures</h3><p className="muted">Teacher absent? Select the substitute and update only that lecture.</p></div></div><div className="table-wrap"><table><thead><tr><th>Day</th><th>Time</th><th>Subject</th><th>Teacher</th><th>Class</th><th>Room</th><th>Substitute</th><th/></tr></thead><tbody>{lectures.map(x=><tr key={x.id}><td>{x.day_of_week}</td><td><b>{x.start_time}–{x.end_time}</b></td><td><b>{x.subject_name}</b></td><td>{x.teacher_name}</td><td>{x.class_name}</td><td>{x.room_number}</td><td><select className="field" value={substitute[x.id]||''} onChange={e=>setSubstitute({...substitute,[x.id]:+e.target.value})}><option value="">Select substitute</option>{teachers.filter(t=>t.name!==x.teacher_name).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>{subMsg[x.id]&&<small className={subMsg[x.id]==='Substitute updated'?'success-text':'error-text'}>{subMsg[x.id]}</small>}</td><td><div className="action-row"><button className="primary-btn compact" onClick={()=>assignSubstitute(x.id)}>Update</button><button className="icon-btn danger" onClick={()=>onDelete(x.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>{!lectures.length&&<div className="empty">No timetable entries found.</div>}</div></div></section>}

function ImportCSV({onDone}:{onDone:(x:string)=>void}){const [text,setText]=useState(''),[fileName,setFileName]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState('');const readFile=(file:File)=>{if(!file.name.toLowerCase().endsWith('.csv'))return setError('Please choose a .csv file.');setError('');setFileName(file.name);const r=new FileReader();r.onload=()=>setText(String(r.result||''));r.readAsText(file)};async function submit(){if(!text.trim())return setError('Choose a CSV file or paste CSV data.');setBusy(true);setError('');setSuccess('');try{const blob=new Blob([text],{type:'text/csv;charset=utf-8'});const formData=new FormData();formData.append('file',blob,fileName||'timetable.csv');const r=await api.post('/timetable/import',formData,{headers:{'Content-Type':'multipart/form-data'}});const created=r.data.created_lines?.length||0,updated=r.data.updated_lines?.length||0,errors=r.data.errors?.length||0;const message=`Timetable replaced successfully: ${created} new, ${updated} updated${errors?`, ${errors} invalid row(s) skipped`:''}.`;setSuccess(message);onDone(message);window.dispatchEvent(new CustomEvent('timetable-imported'))}catch(e:any){setError(e.response?.data?.detail||'CSV import failed.')}finally{setBusy(false)}}return <section className="import-page"><div className="import-hero"><div><span className="eyebrow"><Upload size={14}/> DATA IMPORT</span><h2>Import your timetable</h2><p>Importing replaces the previous timetable and refreshes dashboard views automatically.</p></div><Upload size={32}/></div><div className="card import-card"><div className="drop-zone"><input id="csv-file" type="file" accept=".csv,text/csv" className="file-input" onChange={e=>{const f=e.target.files?.[0];if(f)readFile(f)}}/><label htmlFor="csv-file" className="drop-content"><span className="upload-orb"><Upload size={25}/></span><strong>{fileName||'Drop your CSV file here'}</strong><span>{fileName?'File loaded and ready to import.':'or click to browse'}</span></label></div><textarea value={text} onChange={e=>{setText(e.target.value);setFileName('Pasted CSV')}} className="csv-editor" placeholder="day,start_time,end_time,subject,faculty,room,section,semester\nMonday,09:00,10:00,Data Structures,Dr. Anjali Sharma,C-101,CSE-A,3"/><div className="import-footer"><span className="muted">Accepted standard or friendly timetable CSV format.</span><button disabled={busy} onClick={submit} className="primary-btn compact"><Upload size={17}/>{busy?'Importing…':'Import CSV'}</button></div>{success&&<div className="import-success">✓ {success}</div>}{error&&<div className="import-error">{error}</div>}</div></section>}

function Root(){const [user,setUser]=useState<User|null>(null);useEffect(()=>{if(localStorage.getItem('token'))api.get('/auth/me').then(r=>setUser(r.data)).catch(()=>localStorage.removeItem('token'))},[]);return user?<App user={user} onLogout={()=>setUser(null)}/>:<Login onLogin={setUser}/>}
createRoot(document.getElementById('root')!).render(<Root/>)
